### PR TITLE
Split individual Newsletter pages into html files

### PR DESCRIPTION
**Pull request by nishkalprakash**
Done splitting newsletter pages into individual files.
The `handler.js` file has been modified to handle the new file structure.
It will look for `target` folder and `target.njk` file will be loaded as the template.
The `target` folder will contain all the individual html files as well as the `target.njk` file.

### CODE REVIEW

**Comment by Goose-Of-War** [comment]
image
When it faccha moment :|

**Comment by Goose-Of-War** [comment]
@nishkalprakash why import fs again as fss?

**Comment by nishkalprakash** [comment]
dont get me started on that

i spend hours trying to resolve the promise that is fs( = require(fs).promise)

Objective: 
  Run a fs.readdir to read all files in `target` path
  But fs is an asyc fucntion which isnt executed by this tread

So when I tried to rerun a readdir inside another readdir it just didnt work...

finally i gave up and reloaded the non promise version into fss FFS...

**Review by PartMan7 — COMMENTED** [review]
Umm don't use Sync fs functions in requests; use the async versions

**Comment by nishkalprakash** [comment]
Please go ahead and change it as required 

It was beyond me to use the async conterpart.

**Comment by nishkalprakash** [comment]
just change `readdirSync` fucntion to `readdir` and get it to work.

**Comment by Goose-Of-War** [comment]
image
> File Name: Serial Experiments Lain (by Anmol)

> File content: Kumo Desu Ga (by Parth)

This is gonna take a while...

**Comment by nishkalprakash** [comment]
Oh shi...

**Comment by nishkalprakash** [comment]
> image
> 
> > File Name: Serial Experiments Lain (by Anmol)
> 
> > File content: Kumo Desu Ga (by Parth)
> 
> This is gonna take a while...


Good Catch.

Have rechecked all files.

It should be fine now.
Still do the sanity check once again.

Trying for async file read for 5 mins then giving up.

**Comment by Goose-Of-War** [comment]
> > image
> > > File Name: Serial Experiments Lain (by Anmol)
> > 
> > 
> > > File content: Kumo Desu Ga (by Parth)
> > 
> > 
> > This is gonna take a while...
> 
> Good Catch.
> 
> Have rechecked all files.
> 
> It should be fine now. Still do the sanity check once again.
> 
> Trying for async file read for 5 mins then giving up.

Much AFK indeed

**Comment by PartMan7** [comment]
Will see if I can review this tomorrow

**Review by Goose-Of-War — APPROVED** [review]
Need to fix Oct-2 cover page styling and that of the crossword, but I guess that's for another PR.

**Pull request merged**
