### PR TITLE
files compressed

### PR DESCRIPTION
**Pull request by Markio125**
image files have been compressed

### CODE REVIEW

**Review by Goose-Of-War — CHANGES_REQUESTED** [review]
all files should be less than 200kb in size (max permissible size 250kb, worst case scenario)

**Review by ItsAnkan — CHANGES_REQUESTED** [review]
202407-04, 05, 06, 07, 11, 13, 15
All are above 300kb

And as senpai said, you may as well compress it to be below 250kb

**Review by Goose-Of-War — APPROVED** [review]
seems good

**Comment by Goose-Of-War** [comment]
please stop using this branch and make branches for each specific work ;-;

**Review by ItsAnkan — APPROVED** [review]
good

**Comment by ItsAnkan** [comment]
btw... did you change the hypes ?

**Pull request merged**
