### PR TITLE
Frontend Optimizations

### PR DESCRIPTION
**Pull request by KarmaAkaB**

### CODE REVIEW

**Review by Goose-Of-War — CHANGES_REQUESTED** [review]
image
We need the black on hover. Otherwise, the background image is visible

**Review by ItsAnkan — CHANGES_REQUESTED** [review]
Overlay not showing on hover, fix it onegai

**Comment by Goose-Of-War** [comment]
You know you don't have to reference the issue every time, right?

**Comment by ItsAnkan** [comment]
Looks good, but the black overlay suddenly appearing looks a bit weird, should we fix it ?

https://github.com/kgpmask/MASK/assets/93087057/d5eb0c38-eb0d-4369-880a-650d384544d9

**Review by ItsAnkan — CHANGES_REQUESTED** [review]
Soo.... uhhh, see this video (edited code so that image doesn't get bigger), you see the black background that appears on hover, make it so that the background also grows with the image, or else that looks weird.

You could do that by creating another div inside the image container, and scaling it as the image is scaled on hover, or there are other ways, aapke marzi.
**DO this before EOD, or goos gonna bash me ;-;**

@KarmaAkaB (pinging you just in case)
@karma_aka_chikin#9715 (discord ping, idk if this works or not)

https://github.com/kgpmask/MASK/assets/93087057/e36318df-f375-4c1f-9392-ec5fee9942d0

**Comment by Goose-Of-War** [comment]
:harold:

**Review by ItsAnkan — APPROVED** [review]
This is okay !
Good job Soumil

**Comment by Goose-Of-War** [comment]
> This is okay ! Good job Soumil

Yeet. Merge it, Mr Lawyer

**Pull request merged**
