### PR TITLE
Webhook additions

### PR DESCRIPTION
**Pull request by destryptor**
Next time, remind me to add a description

(I like kids BTW)

### CODE REVIEW

**Comment by destryptor** [comment]
Well this is what i thought the issue means, for now. Will make changes as required

**Comment by Goose-Of-War** [comment]
image
This is how it looks like now ig?

**Comment by Goose-Of-War** [comment]
First of "Member of IIT Kharagpur" question needs to be updated. At least the wording (contact MN I guess)

**Comment by Goose-Of-War** [comment]
Secondly, you can use the normally generated localestring too, as long as the timezone is appropriately set. (This is again kinda redundant I guess considering Discord messages, which is needed for submission management in gov portal... when is this coming up BTW?)

**Review by Goose-Of-War — CHANGES_REQUESTED** [review]
Honestly, just reposition the "Member of KGP" or whatever it is going to be somewhere else. Otherwise, it's fine I guess

**Review by Goose-Of-War — APPROVED** [review]
Looks good

**Pull request merged**
