### PR TITLE
Release 3.2.8

### PR DESCRIPTION
**Pull request by Goose-Of-War**
Note to self: Review after every new commit (except version++)

### CODE REVIEW

**Comment by Goose-Of-War** [comment]
@nishkalprakash can you send it again? For me, the page scrolls down a bit more after the navbar thingy you showed

**Comment by Goose-Of-War** [comment]
And can you send the breaking ~~bad~~ image once again?

**Comment by Goose-Of-War** [comment]
@nishkalprakash don't send the image before it finishes uploading ;-;

**Comment by nishkalprakash** [comment]
Ok

Everything looks fine now.

Great Job.

**Review by nishkalprakash — APPROVED** [review]

**Pull request merged**
