### PR TITLE
Release 3.3.7

### PR DESCRIPTION
**Pull request by Goose-Of-War**

### CODE REVIEW

**Review by nishkalprakash — APPROVED** [review]

**Review by nishkalprakash — CHANGES_REQUESTED** [review]
According to the commit msg,
You are sending out tasks on 9th but the apply now button is still visible

**Review by nishkalprakash — APPROVED** [review]
Ok, according to the announcement group, i understand that you mean to collect responses until 9th
so you can merge these changes

**Comment by Goose-Of-War** [comment]
MFW 🥸

**Comment by PartMan7** [comment]
LGTM

<small>Wheeeee</small>

**Comment by Goose-Of-War** [comment]
Nani the hecc?

**Comment by nishkalprakash** [comment]
> Nani the hecc?

LGTM = Looks Good To Me?

**Comment by Goose-Of-War** [comment]
Oh god this ain't merged yet 💀

**Pull request merged**
