### PR TITLE
Dependency version upgrades

### PR DESCRIPTION
**Pull request by Goose-Of-War**
A major change. Quite a few of our libraries and modules have gone through a version upgrade. I want some people to review the whole site and see if it's fine with how it is right now.

### CODE REVIEW

**Comment by Goose-Of-War** [comment]
Also, yay #200 🥳

**Comment by ItsAnkan** [comment]
this is not related to this PR, but anime-seekers page doesnt work, fix it here itself ig

**Comment by Goose-Of-War** [comment]
image
Nani the heck

**Review by ItsAnkan — APPROVED** [review]
Looks okay, nothing breaks.
You can fix the `events/seekers-quest` route, or make a separate issue and do it.

**Review by ItsAnkan — APPROVED** [review]
All good to go 👍

**Pull request merged**
