### PR TITLE
Insta Artworks

### PR DESCRIPTION
**Pull request by ItsAnkan**
aaaaaaaa, took a while

### CODE REVIEW

**Comment by Goose-Of-War** [comment]
Mongo database deets need human names and not Instagram IDs...

**Comment by Goose-Of-War** [comment]
Also, two more things
1. Compress files to 256KB at most
2. Add lazy loading to images

**Comment by ItsAnkan** [comment]
> Mongo database deets need human names and not Instagram IDs...

some people donot have their names in the IG account, or some IG accounts are invalid

**Comment by ItsAnkan** [comment]
Test database updated, please update the prod one goos, onegai 🥺

**Comment by Goose-Of-War** [comment]
Need to add one more artwork which will be added to Insta today. Then will merge

**Pull request merged**
