### PR TITLE
Rename mask-tech to kgpmask

### PR DESCRIPTION
**Pull request by PartMan7**
@ItsAnkan get sniped

### CODE REVIEW

**Comment by Goose-Of-War** [comment]
@PartMan7 where is the fallback URL be defined? iirc, won't the command be run from this?
(Line 8)
image

**Comment by PartMan7** [comment]
> @PartMan7 where is the fallback URL be defined? iirc, won't the command be run from this? (Line 8) image

credentials.json

**Comment by PartMan7** [comment]
Actually wait yeah good point I'll add it to the docker env

**Comment by PartMan7** [comment]
(Also the conversation should've been on #95)

**Pull request merged**
