### PR TITLE
Loading screen

### PR DESCRIPTION
**Pull request by Goose-Of-War**
Adds a loading screen using a macro.
Displays "Loading... >_<" with the number of dots changing per second (JS interval)
After 20 seconds, shows a small text telling to check the network.
Currently on the events and newsletters page. Will be added to members page too

### CODE REVIEW

**Comment by Goose-Of-War** [comment]
Members page has it too.
@kgpmask/review can you review this onegai

**Comment by nishkalprakash** [comment]
It works well on members.
Have checked with "Slow 3G" setting.

Can we also have the loading screen when we click on the previous members "2022-23" button as well?

**Comment by Goose-Of-War** [comment]
> It works well on members. Have checked with "Slow 3G" setting.
> 
> Can we also have the loading screen when we click on the previous members "2022-23" button as well?

I didn't get you

**Comment by nishkalprakash** [comment]
Oh wait,
it has the loading screen there as well.

nvm,
Good work.

**Review by nishkalprakash — APPROVED** [review]

**Pull request merged**
