### PR TITLE
November Newsletter

### PR DESCRIPTION
**Pull request by SachdevJai**

### CODE REVIEW

**Comment by Goose-Of-War** [comment]
@SachdevJai description and cover page wher?

**Comment by Goose-Of-War** [comment]
image
Need space here

**Comment by Goose-Of-War** [comment]
image
Was this supposed to have the same image only?

**Comment by SachdevJai** [comment]
the images are not supposed to be the same
they are placeholders as i said i asked the freshers for links but not all of them have responded 
ill put them up asap

**Comment by SachdevJai** [comment]
@Goose-Of-War done i think 
review pls

**Comment by Goose-Of-War** [comment]
Ugh... at this point, I'll leave it to Dillip

**Review by Goose-Of-War — APPROVED** [review]
Dillip's call. Will be edited in dev

**Pull request merged**
