### PR TITLE
Release 3.2.6

### PR DESCRIPTION
**Pull request by Goose-Of-War**
# Major Highlights:
- ## Events:  
Articles about all our previous events instead of those two quizzes.
- ## Governor Portal (v1):  
A portal for adding posts and polls directly to the database rather than using Compass or something.  
- ## Under Maintenance Page:  
Since we seem to be breaking the server a bit too much as of late

### CODE REVIEW

**Comment by Goose-Of-War** [comment]
@nishkalprakash T_T

**Comment by nishkalprakash** [comment]
Checking PDS end sems copies.
It takes ages.

**Comment by Goose-Of-War** [comment]
> Checking PDS end sems copies.
> It takes ages.

Gib @SachdevJai the D

**Comment by nishkalprakash** [comment]
All ok.

**Comment by nishkalprakash** [comment]
I can't give the green signal on the phone. Need a pc.

**Review by nishkalprakash — APPROVED** [review]
Prob ok to merge.
If something breaks blame Ankan.

**Comment by ItsAnkan** [comment]
> Prob ok to merge.
> If something breaks blame Ankan.

Why me.. wat did I do 😢

**Comment by Goose-Of-War** [comment]
> Prob ok to merge. If something breaks blame Ankan.

I thought we blaming zai?

**Pull request merged**
