### PR TITLE
Release 3.1.4

### PR DESCRIPTION
**Pull request by Goose-Of-War**
- Revert /events 
- Added an artwork from March

### CODE REVIEW

**Comment by Goose-Of-War** [comment]
Gaah what's with this Schrodinger's tests????
image

**Comment by PartMan7** [comment]
image
The ones on main are the ones that are failing; investigate

**Comment by Goose-Of-War** [comment]
> image The ones on main are the ones that are failing; investigate

Wait... So pull_request checks `main` and not `dev`?
Ah, then only the merge can fix it ig, considering how [event.kgpmask.club](https://event.kgpmask.club) ain't running anything

**Comment by Goose-Of-War** [comment]
@PartMan7 I know we have some other stuff happening too, but we need to merge this branch for the normal quiz and stuff to operate as usual

**Review by PartMan7 — COMMENTED** [review]
There is a LOT of work needed before this is mergeable; indentation on newsletters is atrocious, there's a LOT of repeated code (newsletters PR should not have been merged)

**Comment by PartMan7** [comment]
Honestly I should remove the pull_request on main requirement; it won't really do much except throw false negatives

**Comment by PartMan7** [comment]
Wait why is this - what - :confusion:

**Comment by PartMan7** [comment]
Oh crap

**Review by PartMan7 — COMMENTED** [review]
...how did this happen

**Review by PartMan7 — APPROVED** [review]
Approved on the condition that we work on fixing stuff ASAP

**Pull request merged**
