### PR TITLE
hmm

### PR DESCRIPTION
**Pull request by SachdevJai**
i dont get the issue tbh 
it works for me

### CODE REVIEW

**Comment by Goose-Of-War** [comment]
Gaah
image

**Comment by Goose-Of-War** [comment]
@SachdevJai I ain't mergin this until you answer 🙂

**Comment by SachdevJai** [comment]
whats the question doe?

**Comment by Goose-Of-War** [comment]
Where did it go ;-;

**Comment by Goose-Of-War** [comment]
image
Somehow it's there in the Review

**Comment by SachdevJai** [comment]
lets say if the parent element has value ' jai ' and its child element has value 'vindunram' trimming innertext would only trim the first space of ' jai ' and giv 'jai ' and 'vidunram' ????????? amirit

**Comment by Goose-Of-War** [comment]
> 'vindunram'

**Comment by Goose-Of-War** [comment]
mood

**Comment by Goose-Of-War** [comment]
Anyway, you get half points. I'll merge it

**Pull request merged**
