### PR TITLE
Release 3.2.0

### PR DESCRIPTION
**Pull request by Goose-Of-War**
Added insta artworks from a few batches back

### CODE REVIEW

**Review by PartMan7 — CHANGES_REQUESTED** [review]
Looks mostly good; though if possible please get this done: https://web.dev/browser-level-image-lazy-loading/#images-should-include-dimension-attributes

**Comment by PartMan7** [comment]
Renamed to the right version. Also, approval after fixing the mentioned issue.

**Comment by Goose-Of-War** [comment]
@ItsAnkan I thought I told you to get stuff merged once you're done with it -_-

**Comment by ItsAnkan** [comment]
Really ;-;

**Review by PartMan7 — APPROVED** [review]
Alright this should be enough for now; next release should fix tests

**Pull request merged**
